config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  # コントローラのアクションが実行される前に実行する => indexアクション以外はmove_to_indexメソッドが読み込まれる
  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
  end

  def create
    Tweet.create(text: tweet_params[:text], user_id: current_user.id)
    redirect_to root_path, notice: '投稿が完了しました'
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
    redirect_to root_path, notice: '投稿の削除が完了しました'
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params) if tweet.user_id == current_user.id
    redirect_to root_path, notice: '編集が完了しました'
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  private
  def tweet_params
    params.permit(:name, :text)
  end

  # ユーザーがサインインしてない時、indexアクションを実行する
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>MiniApp</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav style="padding: 0 5px;" class="red darken-1">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo center">mini app</a>
        <% if user_signed_in? %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to "投稿する", new_tweet_path, class: 'post' %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
            <li><%= link_to "新規登録", new_user_registration_path, class: 'post'%></li>
          </ul>
        <% end %>
      </div>
    </nav>

    <%= yield %>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <div class="hiddendiv common"></div>
  </body>

</html>

app/views/tweets/_tweet.html.erb
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div class="card grey lighten-5 z-depth-1">
      <div class="card-content black-text">
        <%= simple_format(tweet.text) %>
      </div>
      <div class="card-action">
        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="row" style="padding-top: 50px;">
<div class="col s12 m6 offset-m3">
  <h1>
    Editing tweet
  </h1>
  <%= form_with url: tweet_path, method: :patch, lacal: true do |form| %>
    <div class="field">
      <label for="tweet_text">Text</label>
      <%= form.text_area :text %>
    </div>      
    <div class="actions">
      <%= form.submit :commit %>
    </div>
  <% end %>
</div>
</div>

app/views/tweets/index.html.erb
<% @tweets.each do |tweet| %>
  <%= render partial: "tweet", locals: {tweet: tweet } %>
<% end %>
<div class="container center">
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="row" style="padding-top: 50px;">
<div class="col s12 m6 offset-m3">
  <h1>
    New tweet
  </h1>
  <%= form_with url: tweets_path, method: :post, local: true do |form| %>
    <div class="field">
      <label for="tweet_text">Text</label>
      <%= form.text_area :text %>
    </div>      
    <div class="actions">
      <%= form.submit :send %>
    </div>
  <% end %>
</div>
</div>